twig:
    default_path: '%kernel.project_dir%/templates'
#    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        patreon_client_id: "%patreon_client_id%"
        twitch_client_id: "%twitch_client_id%"
        downloadsService: '@App\Service\DownloadService'
        mapperService: '@App\Service\MapperService'
        scoreService: '@App\Service\ScoreService'
        rankingScoreService: '@App\Service\RankingScoreService'
        songService: '@App\Service\SongService'
        songDifficultyNotationService: '@App\Service\SongDifficultyNotationService'
        statisticService: '@App\Service\StatisticService'
        membershipService: '@App\Service\MembershipService'
        grantedService: '@App\Service\GrantedService'
        voteService: '@App\Service\VoteService'
    form_themes:
        - 'form/rating_type.html.twig'
